// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmwdgQ8orDZRxm67jDDSyPS43iF6dv504',
    appId: '1:523538994182:web:9bb15bb0f6cbeca2765f87',
    messagingSenderId: '523538994182',
    projectId: 'alhadiqa-project',
    authDomain: 'alhadiqa-project.firebaseapp.com',
    storageBucket: 'alhadiqa-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWo6msDDeHRdrVXAzmkuyd_K60FpwGvJQ',
    appId: '1:523538994182:android:6b6b447018f753c7765f87',
    messagingSenderId: '523538994182',
    projectId: 'alhadiqa-project',
    storageBucket: 'alhadiqa-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKlvyMLrGMoZLVQCQ-minoWjvWzEOwDB0',
    appId: '1:523538994182:ios:7e14f094c7f93ea1765f87',
    messagingSenderId: '523538994182',
    projectId: 'alhadiqa-project',
    storageBucket: 'alhadiqa-project.firebasestorage.app',
    iosBundleId: 'com.example.alhadiqa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKlvyMLrGMoZLVQCQ-minoWjvWzEOwDB0',
    appId: '1:523538994182:ios:7e14f094c7f93ea1765f87',
    messagingSenderId: '523538994182',
    projectId: 'alhadiqa-project',
    storageBucket: 'alhadiqa-project.firebasestorage.app',
    iosBundleId: 'com.example.alhadiqa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmwdgQ8orDZRxm67jDDSyPS43iF6dv504',
    appId: '1:523538994182:web:f213ab31923fa796765f87',
    messagingSenderId: '523538994182',
    projectId: 'alhadiqa-project',
    authDomain: 'alhadiqa-project.firebaseapp.com',
    storageBucket: 'alhadiqa-project.firebasestorage.app',
  );
}
